//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhanaKhajana
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public int DiscountId { get; set; }
        public int ProductId { get; set; }
        public double DiscountPercent { get; set; }
    }
}
